### ISSUE TITLE
Requesting for data

### ISSUE THREAD

**Issue by shardulkulkarni14** [Wangmmstar/Hospital_Scene_Data#1]
Hi @Wangmmstar @dhu5-utk ,

I have filled the google form requesting for the data, I am in need of this data for my Master Thesis. I did not receive any reply regarding the dataset, can you please help me in getting access to the dataset. 

Thank you very much in advance, I would be really grateful to hear back from you.

Best Regards,
Shardul Kulkarni

**Comment by shardulkulkarni06** [comment]
Thank you for providing the dataset

**Comment by shardulkulkarni14** [comment]
Thank you for providing the dataset
